### ISSUE TITLE
Usage Example

### ISSUE THREAD

**Issue by nelsonic** [hapijs/poop#36]
Hi @cjihrig,
Is there a *usage example* (or guide/tutorial/blogpost) to help *beginners* get started using **Poop**?
I read the [source](https://github.com/hapijs/poop/blob/master/lib/index.js) and 
[tests](https://github.com/hapijs/poop/blob/master/test/index.js) to understand the module, but feel others would benefit from a simple explanation.
I can send a PR with some copy if you don't have time to write it.

**Comment by Marsup** [comment]
IMHO there can hardly exist an example since all you have to do is register the module.

**Comment by cjihrig** [comment]
I agree with @Marsup that there isn't a ton to document with poop. However, the existing docs are pretty sparse, so any upgrades would be welcome.
