### ISSUE TITLE
Option to not create a heapdump

### ISSUE THREAD

**Issue by rquez** [hapijs/poop#37]
Hi, this is a great tool. I find it very useful. Just one question, is there an option to not create a heapdump? I just want the poop.log, but I don't want this huge heapdump file. Thanks.

**Comment by cjihrig** [comment]
The primary purpose of poop is to take a heapdump. Otherwise, you're just writing an error and date to a file on uncaught exception. I don't see any harm in it though, so I'll take a PR for it.

**Comment by cjihrig** [comment]
Closing for lack of interest. This doesn't really make a lot of sense anyway.
