### ISSUE TITLE
Add option for heapdump path

### ISSUE THREAD

**Issue by geek** [hapijs/poop#45]
Need to be able to specify the location where a heapdump is created

**Comment by lloydbenson** [comment]
You can via the logFile attribute.

**Comment by lloydbenson** [comment]
https://github.com/hapijs/poop#logpath

**Comment by geek** [comment]
That is documented as the path where logs are stored, not the heapdump file.

**Comment by lloydbenson** [comment]
Ah!  Yes, it just creates it as cwd() it would be nice to specify this location.

**Comment by andreftavares** [comment]
+1 for this

**Comment by cjihrig** [comment]
A PR is welcome

**Comment by andreftavares** [comment]
https://github.com/hapijs/poop/pull/46 :)

**Comment by cjihrig** [comment]
Closed by #46
