### ISSUE TITLE
server shutdown on process uncaught exception

### ISSUE THREAD

**Issue by pgte** [hapijs/poop#49]
By looking at [the process uncaught exception handler code](https://github.com/hapijs/poop/blob/master/lib/index.js#L40), the process is being shutdown immediately after the heapdump.

I think that one preferable way of doing would be to close the server (not accepting further connections), wait for all the pending requests to finish (with a timeout) and *then* exiting the process.

Is this something you might be interested in? If so, I can submit a PR.

**Comment by cjihrig** [comment]
I don't think it's a good idea to continue processing the existing requests. If you reach the `uncaughtException` handler, then you can't be certain of your application's state. The Node documentation states:

> 'uncaughtException' should be used to perform synchronous cleanup before shutting down the process.

If you continue processing the existing requests, there is likely to be asynchronous processing involved.

**Comment by pgte** [comment]
@cjihrig I don't see any risk in _not_ killing customer requests mid-transaction, quite the contrary...
@cjihrig can you elaborate, objectively, what would the risks be?

**Comment by devinivy** [comment]
The risks are effectively unknown, since the error was not handled (so, it was not anticipated).  The idea is that your app is in a brittle state and may do "the wrong thing".  It's a crappy example, but imagine an uncaught error in a security layer that implies that access control logic is broken and requires some sort of repair/resetting.  You wouldn't want other requests to complete and possibly share private information.

**Comment by cjihrig** [comment]
The risks are that the [Node documentation](https://nodejs.org/api/process.html#process_event_uncaughtexception) explicitly say not to do this. If anything, you should have error handling somewhere else in your application to prevent `uncaughtExceptions` from occurring. Poop only exists to take a heapdump.

**Comment by pgte** [comment]
I know that it may be scary to allow the process to go on until all the requests are complete, but sometimes I may be willing to take the risk so that the on-going requests finish. This module is just for the times when the risk is not acceptable, and that's ok. Closing this one.
